### ISSUE TITLE
Test Ivan

### ISSUE THREAD

**Issue by cayomesquita** [cayomesquita/ciccc_202_final_project#3]
See the workflow of this issue in the kanban.

See the issue on the kanban

Move the card of this issue in the kanban to tab in progress

See the issue on the kanban

Close the issue

See the issue on the kanban

Create a issue

on the rigth setting

assign to someone
set the label
set the project

that's a hands-on to know how it works.

**Comment by HermiloOrtega** [comment]
Remember to close the issue Ivan
