### ISSUE TITLE
T: Street move

### ISSUE THREAD

**Issue by HermiloOrtega** [cayomesquita/ciccc_202_final_project#9]
I already change the texture of the sidewalk and the street but i need to update the loop to show always the same texture in movement.

**Comment by cayomesquita** [comment]
commit cf20bc3345c86558a95726f58bf60d1d341afa91 (origin/feature-street, feature-street)
Author: Cayo <cayomesquita@gmail.com>
Date:   Tue Mar 31 10:26:08 2020 -0700

    Add Street move
